language: scala
scala:
  - 2.12.3

before_script:
  - openssl s_client -connect forge-cogit.ign.fr:443 </dev/null 2>/dev/null|openssl x509 -outform PEM >mycertfile.pem
  - keytool -v -alias mavensrv -import -file mycertfile.pem -keypass changeit -keystore /etc/ssl/certs/java/cacerts -noprompt
